### PR TITLE
dist.ini: include Makefile.PL in git dir

### PR DESCRIPTION
**Pull request by robn**
For easy building from a git clone in a dzil-less environment.

### CODE REVIEW

**Comment by wolfsage** [comment]
Thanks I have a note to take care of this tomorrow

**Comment by wolfsage** [comment]
@robn Did `dzil build` work for you?

I need this in dist.ini for it to function:
```
name    = Email-Footer
author  = Matthew Horsfall (alh) <WolfSage@gmail.com>
license = Perl_5
copyright_holder = Matthew Horsfall
copyright_year   = 2016

[@Filter]
-bundle = @RJBS
-remove = Git::GatherDir

[CopyFilesFromBuild]
copy = Makefile.PL

[Git::GatherDir]
exclude_filename = Makefile.PL
```

**Comment by robn** [comment]
It did; that's what generated the Makefile.PL I committed!

Your way looks fine; I do something similar in my own Perl stuff. (GatherDir, not Git::GatherDir, but same idea).

I don't actually care; I just need to be able to install without needing dzil around.

**Comment by wolfsage** [comment]
Right but after you add the Makefile.PL, I can never get it to build without my changes because it complains about adding it twice. Weird. I'll just use my variant, thanks

**Comment by wolfsage** [comment]
Merged, thanks

**Pull request closed without merging**
